### ISSUE TITLE
Assertion failed on the build of static aabb tree of edyn library

### ISSUE THREAD

**Issue by jcbecker** [xissburg/edyn-testbed#1]
The build of edyn-testbed and its dependencies was successful, but one assertion has failed on execution.

`CMAKE_BUILD_TYPE` of edyn-testbed built as default(Debug).

Tested with edyn version [5cd0ad2](https://github.com/xissburg/edyn/commit/5cd0ad2fbf55277ac06042602153e1cb439e0f3d) and [7875f67](https://github.com/xissburg/edyn/commit/7875f67cf38ba33031d2297dc5dfbda9c8e6c81c)

Assertion on line 76 of the file /edyn/include/edyn/collision/static_tree.hpp.

Error log:
```shell
...
../../../src/bgfx_p.h (4636): BGFX Creating uniform (handle   4) s_tex
../../../src/bgfx_p.h (4636): BGFX Creating uniform (handle   5) u_imageLodEnabled
EDynTestbed: /home/jcbecker/repos/edyn/include/edyn/collision/static_tree.hpp:76: void edyn::static_tree::build(Iterator, Iterator, Func&, uint32_t) [with Iterator = __gnu_cxx::__normal_iterator<edyn::AABB*, std::vector<edyn::AABB> >; Func = edyn::detail::submesh_builder<__gnu_cxx::__normal_iterator<edyn::vector3*, std::vector<edyn::vector3> >, __gnu_cxx::__normal_iterator<short unsigned int*, std::vector<short unsigned int> >, __gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int> > >; uint32_t = unsigned int]: Assertion `aabb_begin != aabb_end' failed.
Segmentation fault (core dumped)
```

**Comment by xissburg** [comment]
I believe that must be because I haven't included the resources in the repo yet and it's trying to load a triangle mesh from file in https://github.com/xissburg/edyn-testbed/blob/master/src/triangle_mesh.cpp . I will add some resource files later using Git LFS.

Perhaps you could either modify the number in front of the sample name at https://github.com/xissburg/edyn-testbed/blob/b1795a3063d5f302bf5444e225ef94e0b0068f06/src/triangle_mesh.cpp#L239 so it won't be loaded first. 

Sorry for this project still being a big mess 🙃. There's still a lot of commented out left over code from a lot of testing and experimentation.

**Comment by xissburg** [comment]
I have added the resources using Git LFS and have also updated and improved the code in the triangle mesh example. One caveat is that the library was recently renamed from _EDyn_ to _Edyn_ so it is possible you could happen to link to the old version of the library.
